# SwiftLint Configuration
# This configuration enforces strict Swift style guidelines and best practices

# Included paths
included:
  - Sources/
  - Tests/

# Excluded paths
excluded:
  - Sources/SwiftralinoWebView/
  - Public/
  - Package.swift
  - .build/
  - Carthage/
  - Pods/
  - DerivedData/

# Analyzer rules (require full compilation)
analyzer_rules:
  - unused_declaration
  - unused_import

# Enabled rules
opt_in_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments for now
  - multiple_closures_with_trailing_closure # Can be useful in some cases

# Rule configurations
line_length:
  warning: 120
  error: 140
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

function_body_length:
  warning: 40
  error: 60

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 60
    error: 80

large_tuple:
  warning: 3
  error: 4

closure_body_length:
  warning: 20
  error: 30

enum_case_associated_values_count:
  warning: 5
  error: 6

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: 'print\('
    message: "Use proper logging instead of print statements"
    severity: warning

  no_force_cast:
    name: "No Force Casts"
    regex: 'as!'
    message: "Use safe casting with 'as?' instead of force casting 'as!'"
    severity: error

  no_force_unwrap:
    name: "No Force Unwrapping"
    regex: '!\s*$'
    message: "Use safe unwrapping instead of force unwrapping"
    severity: warning

# Reporter
reporter: "xcode"

# Strict mode
strict: false

# Warning threshold
warning_threshold: 20 