# SwiftLint Configuration
# This configuration enforces strict Swift style guidelines and best practices

# Included paths
included:
  - Sources
  - Tests

# Excluded paths
excluded:
  - Sources/SwiftralinoWebView # Web component directory
  - .build
  - Package.swift

# Rule Configuration
line_length:
  warning: 120
  error: 140

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 50
  error: 80

type_body_length:
  warning: 300
  error: 400

# Enable additional rules
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call

# Disable problematic rules for distributed actors and experimental code
disabled_rules:
  - todo # Allow TODO comments for now
  - force_cast # Sometimes needed for distributed actors
  - force_try # Sometimes needed for testing and experimental features

# Custom rule configurations
identifier_name:
  min_length:
    warning: 1
    error: 1
  allowed_symbols: ["_"]
  validates_start_with_lowercase: false # Allow for some distributed actor patterns

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: false

vertical_whitespace:
  max_empty_lines: 2

custom_rules:
  # Encourage proper documentation for public APIs
  public_documentation:
    name: "Public Documentation"
    regex: '^\s*public (?:func|var|let|class|struct|enum|protocol|typealias)(?!\s+func\s+test)'
    message: "Public declarations should be documented"
    severity: warning

reporter: "xcode" 