services:
  # Swiftralino headless server
  swiftralino:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swiftralino-server
    ports:
      - "${SWIFTRALINO_HTTP_PORT:-8080}:8080"
      - "${SWIFTRALINO_HTTPS_PORT:-8443}:8443"
    environment:
      # Server configuration
      - SWIFTRALINO_HOST=0.0.0.0
      - SWIFTRALINO_PORT=${SWIFTRALINO_PORT:-8080}
      - SWIFTRALINO_DISABLE_TLS=${SWIFTRALINO_DISABLE_TLS:-false}
      - DOMAIN=${DOMAIN:-localhost}
      
      # Optional: Custom configuration
      - SWIFT_LOG_LEVEL=${SWIFT_LOG_LEVEL:-info}
      - SWIFTRALINO_ENV=${SWIFTRALINO_ENV:-production}
    
    volumes:
      # SSL certificates (required for TLS)
      - ./ssl:/app/ssl:ro
      # Let's Encrypt certificates (if using certbot)
      - ./letsencrypt:/etc/letsencrypt:ro
      # Optional: Mount configuration files
      - ./config:/app/config:ro
      # Optional: Mount persistent data
      - swiftralino-data:/app/data
    
    networks:
      - swiftralino-network
    
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Certbot for Let's Encrypt certificates
  certbot:
    image: certbot/certbot
    container_name: swiftralino-certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot -d ${DOMAIN:-localhost} --email ${CERTBOT_EMAIL:-admin@localhost} --agree-tos --no-eff-email
    profiles:
      - certbot
    depends_on:
      - nginx

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: swiftralino-proxy
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./certbot-webroot:/var/www/certbot
    networks:
      - swiftralino-network
    depends_on:
      - swiftralino
    restart: unless-stopped
    profiles:
      - proxy

volumes:
  swiftralino-data:
    driver: local

networks:
  swiftralino-network:
    driver: bridge 